name: date_field
description: A widget in the form of a field that lets people choose a date, a time or both.
version: 3.0.2
homepage: "https://github.com/GaspardMerten/date_field"
publish_to: "none"

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
