import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'hi_IN': {
          'almirah': 'अलमारी',
          'analytics': 'विश्लेषण',
          'company': 'कंपनी',
          'contact': 'संपर्क सूची',
          'customer': 'ग्राहक',
          'customer_category': 'ग्राहक श्रेणी',
          'customer_category_n': 'ग्राहक\nश्रेणी',
          'diary': 'डायरी',
          'godown': 'गोदाम',
          'item': 'सामान',
          'item_category': 'सामान श्रेणी',
          'item_category_n': 'सामान\nश्रेणी',
          'item_variant': 'सामान का प्रकार',
          'item_variant_n': 'सामान का\nप्रकार',
          'unit': 'मापतोल इकाई',
          'unit_n': 'मापतोल\nइकाई',
          'purchase_order': 'ख़रीद\nआदेश',
          'purchase_order_n': 'ख़रीद\nआदेश',
          'purchased_item': 'ख़रीदा गया सामान',
          'purchased_item_n': 'ख़रीदा गया\nसामान',
          'receipt': 'रसीद',
          'report': 'रिपोर्ट',
          'sales_order': 'सेल्स ऑर्डर',
          'sales_order_n': 'सेल्स\nऑर्डर',
          'store_room': 'स्टोररूम',
          'store_room_n': 'स्टोररूम',
          'supplier': 'सप्लायर',
          'add_almirah': 'अलमारी जोडें',
          'add_company': 'कंपनी जोडें',
          'add_customer': 'ग्राहक जोडें',
          'add_customer_category': 'ग्राहक श्रेणी जोडें',
          'add_godown': 'गोदाम जोडें',
          'add_unit': 'मापतोल इकाई जोडें',
          'add_item': 'सामान जोडें',
          'add_item_category': 'सामान श्रेणी जोडें',
          'add_item_variant': 'सामान का प्रकार जोडें',
          'add_order': 'आर्डर जोडें',
          'add_purchased_item': 'ख़रीदा गया सामान जोड़ें',
          'add_purchase_order': 'ख़रीद आदेश जोड़ें',
          'add_store_room': 'स्टोररूम जोडें',
          'add_supplier': 'सप्लायर जोडें',
          'update_almirah': 'अलमारी अपडेट करें',
          'update_company': 'कंपनी अपडेट करें',
          'update_customer': 'ग्राहक अपडेट करें',
          'update_customer_category': 'ग्राहक श्रेणी अपडेट करें',
          'update_godown': 'गोदाम अपडेट करें',
          'update_item': 'सामान अपडेट करें',
          'update_item_category': 'सामान श्रेणी अपडेट करें',
          'update_item_variant': 'सामान का प्रकार अपडेट करें',
          'update_unit': 'मापतोल इकाई अपडेट करें',
          'update_purchased_item': 'ख़रीदा गया सामान अपडेट करें',
          'update_purchase_order': 'ख़रीद आदेश अपडेट करें',
          'update_store_room': 'स्टोररूम अपडेट करें',
          'update_supplier': 'सप्लायर अपडेट करें',
          'search_almirah_here': 'यहाँ अलमारी खोजें',
          'search_company_here': 'यहां कंपनी खोजें',
          'search_contact_here': 'यहां संपर्क खोजें',
          'search_customer_here': 'यहां ग्राहक खोजें',
          'search_customer_category_here': 'यहां ग्राहक श्रेणी खोजें',
          'search_godown_here': 'यहां गोदाम खोजें',
          'search_unit_here': 'यहां मापतोल इकाई खोजें',
          'search_purchased_item_here': 'यहां ख़रीदा गया सामान खोजें',
          'search_purchase_order_here': 'यहां ख़रीद आदेश खोजें',
          'search_item_here': 'यहाँ सामान खोजें',
          'search_item_category_here': 'यहां सामान श्रेणी खोजें',
          'search_item_variant_here': 'यहाँ सामान का प्रकार खोजें',
          'search_receipt_here': 'यहां रसीद खोजें',
          'search_store_room_here': 'यहां स्टोररूम खोजें',
          'search_supplier_here': 'यहां सप्लायर खोजें',
          'add_almirah_n': 'अलमारी\nजोड़ें',
          'view_almirah_n': 'अलमारी\nदेखें',
          'add_company_n': 'कंपनी\nजोडें',
          'view_company_n': 'कंपनी\nदेखें',
          'add_customer_n': 'ग्राहक\nजोडें',
          'view_customer_n': 'ग्राहक\nदेखें',
          'add_customer_category_n': 'ग्राहक\nश्रेणी\nजोडें',
          'view_customer_category_n': 'ग्राहक\nश्रेणी\nदेखें',
          'add_godown_n': 'गोदाम\nजोडें',
          'view_godown_n': 'गोदाम\nदेखें',
          'add_item_n': 'सामान\nजोडें',
          'view_item_n': 'सामान\nदेखें',
          'add_item_category_n': 'सामान श्रेणी\nजोडें',
          'view_item_category_n': 'सामान श्रेणी\nदेखें',
          'add_item_variant_n': 'सामान का\nप्रकार जोडें',
          'view_item_variant': 'सामान का प्रकार देखें',
          'view_item_variant_n': 'सामान का\nप्रकार देखें',
          'add_unit_n': 'मापतोल इकाई\nजोडें',
          'view_unit_n': 'मापतोल इकाई\nदेखें',
          'add_order_n': 'आर्डर\nजोडें',
          'view_order_n': 'आर्डर\nदेखें',
          'add_purchased_item_n': 'ख़रीदा गया\nसामान जोड़ें',
          'view_purchased_item_n': 'ख़रीदा गया\nसामान देखें',
          'add_purchase_order_n': 'ख़रीद आदेश\nजोड़ें',
          'view_purchase_order_n': 'ख़रीद आदेश\nदेखें',
          'add_supplier_n': 'सप्लायर\nजोडें',
          'view_supplier_n': 'सप्लायर\nदेखें',
          'add_store_room_n': 'स्टोररूम\nजोडें',
          'view_store_room_n': 'स्टोररूम\nदेखें',
          'almirah_success_msg': 'अलमारी को सफलतापूर्वक जोड़ दिया गया है।',
          'company_success_msg': 'कंपनी को सफलतापूर्वक जोड़ दिया गया है।',
          'customer_success_msg': 'ग्राहक को सफलतापूर्वक जोड़ दिया गया है।',
          'customer_category_success_msg':
              'ग्राहक श्रेणी को सफलतापूर्वक जोड़ दिया गया है।',
          'diary_success_msg': 'डायरी को सफलतापूर्वक जोड़ दिया गया है।',
          'godown_success_msg': 'गोदाम को सफलतापूर्वक जोड़ दिया गया है।',
          'unit_success_msg': 'मापतोल इकाई को सफलतापूर्वक जोड़ दिया गया है।',
          'order_success_msg': 'आर्डर को सफलतापूर्वक जोड़ दिया गया है।',
          'purchased_item_success_msg':
              'ख़रीदे गए सामान को सफलतापूर्वक जोड़ दिया गया है।',
          'purchase_order_success_msg':
              'खरीद आदेश को सफलतापूर्वक जोड़ दिया गया है।',
          'item_success_msg': 'सामान को सफलतापूर्वक जोड़ दिया गया है।',
          'item_category_success_msg':
              'सामान श्रेणी को सफलतापूर्वक जोड़ दिया गया है।',
          'item_variant_success_msg':
              'सामान का प्रकार को सफलतापूर्वक जोड़ दिया गया है।',
          'store_room_success_msg': 'स्टोररूम को सफलतापूर्वक जोड़ दिया गया है।',
          'supplier_success_msg': 'सप्लायर को सफलतापूर्वक जोड़ दिया गया है।',
          "almirah_updated_success_msg":
              "अलमारी को सफलतापूर्वक अपडेट कर दिया गया है।",
          'company_updated_success_msg':
              'कंपनी को सफलतापूर्वक अपडेट कर दिया गया है।',
          'customer_updated_success_msg':
              'ग्राहक को सफलतापूर्वक अपडेट कर दिया गया है।',
          'customer_category_updated_success_msg':
              'ग्राहक श्रेणी को सफलतापूर्वक अपडेट कर दिया गया है।',
          'diary_updated_success_msg':
              'डायरी को सफलतापूर्वक अपडेट कर दिया गया है।',
          'godown_updated_success_msg':
              'गोदाम को सफलतापूर्वक अपडेट कर दिया गया है।',
          'unit_updated_success_msg':
              'मापतोल इकाई को सफलतापूर्वक अपडेट कर दिया गया है।',
          'order_updated_success_msg':
              'आर्डर को सफलतापूर्वक अपडेट कर दिया गया है।',
          'purchased_item_updated_success_msg':
              'ख़रीदे गए सामान को सफलतापूर्वक अपडेट कर दिया गया है।',
          'purchase_order_updated_success_msg':
              'खरीद आदेश को सफलतापूर्वक अपडेट कर दिया गया है।',
          'item_updated_success_msg':
              'सामान को सफलतापूर्वक अपडेट कर दिया गया है।',
          'item_variant_updated_success_msg':
              'सामान का प्रकार को सफलतापूर्वक अपडेट कर दिया गया है।',
          'item_category_updated_success_msg':
              'सामान श्रेणी को सफलतापूर्वक अपडेट कर दिया गया है।',
          'store_room_updated_success_msg':
              'स्टोररूम को सफलतापूर्वक अपडेट कर दिया गया है।',
          'supplier_updated_success_msg':
              'सप्लायर को सफलतापूर्वक अपडेट कर दिया गया है।',
          "no_almirah_found": "कोई अलमारी नहीं मिली है।",
          "no_company_found": "कोई कंपनी नहीं मिली है।",
          "no_contact_found": "कोई संपर्क नहीं मिली है।",
          "no_customer_found": "कोई ग्राहक नहीं मिला है।",
          "no_customer_category_found": "कोई ग्राहक श्रेणी नहीं मिली है।",
          "no_diary_found": "कोई डायरी नहीं मिली है।",
          "no_godown_found": "कोई गोदाम नहीं मिला है।",
          "no_order_found": "कोई आर्डर नहीं मिला है।",
          "no_purchased_item_found": 'कोई ख़रीदा गया सामान नहीं मिला है।',
          "no_purchase_order_found": 'कोई खरीद आदेश नहीं मिला है।',
          "no_item_found": 'कोई सामान नहीं मिला है।',
          "no_item_category_found": 'कोई सामान श्रेणी नहीं मिला है।',
          "no_item_variant_found": 'कोई सामान का प्रकार नहीं मिला है।',
          "no_store_room_found": 'कोई स्टोररूम नहीं मिला है।',
          "no_supplier_found": 'कोई सप्लायर नहीं मिला है।',
          "no_unit_found": 'कोई मापतोल इकाई नहीं मिला है।',
          'no_almirah': 'अभी तक कोई अलमारी नहीं जोड़ा गया है।',
          'no_company': 'अभी तक कोई कंपनी नहीं जोड़ा गया है।',
          'no_customer': 'अभी तक कोई ग्राहक नहीं जोड़ा गया है।',
          'no_customer_category': 'अभी तक कोई ग्राहक श्रेणी नहीं जोड़ा गया है।',
          'no_diary': 'अभी तक कोई डायरी नहीं जोड़ा गया है।',
          'no_godown': 'अभी तक कोई गोदाम नहीं जोड़ा गया है।',
          'no_unit': 'अभी तक कोई मापतोल इकाई नहीं जोड़ा गया है।',
          'no_order': 'अभी तक कोई आर्डर नहीं जोड़ा गया है।',
          'no_purchased_item': 'अभी तक कोई खरीदा हुआ सामान नहीं जोड़ा गया है।',
          'no_purchase_order': 'अभी तक कोई खरीद आदेश नहीं दिया गया है।',
          'no_item': 'अभी तक कोई सामान नहीं जोड़ा गया है।',
          'no_item_category': 'अभी तक कोई सामान श्रेणी नहीं जोड़ा गया है।',
          'no_item_variant': 'अभी तक कोई सामान का प्रकार नहीं जोड़ा गया है।',
          'no_store_room': 'अभी तक कोई स्टोररूम नहीं जोड़ा गया है।',
          'no_supplier': 'अभी तक कोई सप्लायर नहीं जोड़ा गया है।',
          'add_no_almirah': 'अलमारी जोड़ना शुरू करें।',
          'add_no_company': 'कंपनी जोड़ना शुरू करें।',
          'add_no_customer': 'ग्राहक जोड़ना शुरू करें।',
          'add_no_customer_category': 'ग्राहक श्रेणी जोड़ना शुरू करें।',
          'add_no_diary': 'डायरी लिखना शुरू करें।',
          'add_no_godown': 'गोदाम जोड़ना शुरू करें।',
          'add_no_unit': 'मापतोल इकाई जोड़ना शुरू करें।',
          'add_no_order': 'आर्डर जोड़ना शुरू करें।',
          'add_no_purchased_item': 'ख़रीदा गया सामान जोड़ना शुरू करें',
          'add_no_item': 'सामान जोड़ना शुरू करें।',
          'add_no_item_category': 'सामान श्रेणी जोड़ना शुरू करें।',
          'add_no_item_variant': 'सामान का प्रकार जोड़ना शुरू करें।',
          'add_no_store_room': 'स्टोररूम जोड़ना शुरू करें।',
          'add_no_supplier': 'सप्लायर जोड़ना शुरू करें।',
          'almirah_name': 'अलमारी का नाम',
          'almirah_name_hint': 'अलमारी का नाम दर्ज करें',
          'almirah_row': 'अलमारी का पंक्ति संख्या',
          'almirah_row_hint': 'अलमारी का पंक्ति संख्या दर्ज करें',
          'almirah_column': 'अलमारी का स्तंभ संख्या',
          'almirah_column_hint': 'अलमारी का स्तंभ संख्या दर्ज करें',
          'customer_mobile_number': 'ग्राहक का मोबाइल नंबर',
          'customer_mobile_number_hint': 'ग्राहक का मोबाइल नंबर दर्ज करें',
          'customer_name': 'ग्राहक का नाम',
          'customer_name_hint': 'ग्राहक का नाम दर्ज करें',
          'customer_nick_name': 'ग्राहक का उपनाम',
          'customer_nick_name_hint': 'ग्राहक का उपनाम दर्ज करें',
          'male': 'पुरुष',
          'female': 'महिला',
          'customer_category_name': 'सामान श्रेणी का नाम',
          'customer_category_name_hint': 'सामान श्रेणी का नाम दर्ज करे',
          'column': 'स्तंभ मान',
          'column_hint': 'स्तंभ मान दर्ज करें',
          'company_name': 'कंपनी का नाम',
          'company_name_hint': 'कंपनी का नाम दर्ज करें',
          'customer_address': 'ग्राहक का पता',
          'customer_address_hint': 'ग्राहक का पता दर्ज करें',
          'customer_account_number': 'ग्राहक का खाता संख्या',
          'customer_account_hint': 'ग्राहक का खाता संख्या दर्ज करें',
          'customer_category_hint': 'सही ग्राहक श्रेणी का चयन करें',
          'godown_name': 'गोदाम का नाम',
          'godown_name_hint': 'गोदाम का नाम दर्ज करें',
          'item_name': 'सामान का नाम',
          'item_name_hint': 'सामान का नाम दर्ज करे',
          'item_category_name': 'सामान श्रेणी',
          'item_category_name_hint': 'सामान श्रेणी का नाम दर्ज करे',
          'alternate_name': 'वैकल्पिक नाम',
          'alternate_name_hint': 'वैकल्पिक नाम दर्ज करे',
          'item_description': 'सामान के बारे में विवरण',
          'item_description_hint': 'सामान के बारे में कुछ लिखे',
          'item_category_hint': 'सही सामान श्रेणी का चयन करें',
          'unit_hint': 'मापतोल की इकाई का दर्ज करें',
          'unit_full_name': 'मापतोल इकाई का पूरा नाम:',
          'unit_full_name_hint': 'मापतोल की इकाई का पूरा नाम दर्ज करें',
          'unit_short_name': 'मापतोल इकाई का संक्षिप्त नाम:',
          'unit_short_name_hint': 'मापतोल की इकाई का संक्षिप्त नाम दर्ज करें',
          'minimum_stock_description':
              'मात्रा न्यूनतम स्टॉक से कम होने पर आपको सूचित किया जाएगा',
          'minimum_stock': 'न्यूनतम स्टॉक मात्रा',
          'minimum_stock_hint': 'न्यूनतम स्टॉक मात्रा दर्ज करें',
          'minimum_stock_unit': 'न्यूनतम स्टॉक मात्रा की इकाई',
          'quantity': 'मात्रा',
          'quantity_hint': 'मात्रा दर्ज करें',
          'pincode': 'पिन कोड',
          'pincode_hint': 'छह अंकों का पिन कोड दर्ज करें',
          'purchasing_date': 'खरीदने की तिथि',
          "purchasing_date_hint": "भविष्य की तारीख दर्ज नहीं कर सकते",
          'purchased_quantity': 'खरीदी गई मात्रा',
          'purchased_quantity_hint': 'खरीदी गई मात्रा दर्ज करें',
          "purchased_quantity_unit": 'खरीदी मात्रा की इकाई',
          'purchasing_price': 'खरीदारी कीमत',
          'purchasing_price_hint': 'खरीदारी कीमत दर्ज करें',
          "purchasing_price_unit": "खरीदी कीमत की इकाई",
          'row': 'पंक्ति मान',
          'row_hint': 'पंक्ति मान दर्ज करें',
          "selling_price": "बेचने की कीमत",
          'selling_price_hint': 'बेचने की कीमत दर्ज करें',
          "selling_price_unit": "बेचने की कीमत की इकाई",
          'store_room_name': 'स्टोररूम का नाम',
          'store_room_name_hint': 'स्टोररूम का नाम दर्ज करें',
          'supplier_mobile_number': 'सप्लायर का मोबाइल नंबर',
          'supplier_mobile_number_hint': 'सप्लायर का मोबाइल नंबर दर्ज करें',
          'supplier_name': 'सप्लायर का नाम',
          'supplier_name_hint': 'सप्लायर का नाम दर्ज करें',
          'supplier_nick_name': 'सप्लायर का उपनाम',
          'supplier_nick_name_hint': 'सप्लायर का उपनाम दर्ज करें',
          'supplier_shop_or_business_name': 'Supplier Shop/Business Name',
          'supplier_shop_or_business_name_hint':
              'सप्लायर के दुकान/बिज़नेस का नाम',
          'supplier_address': 'सप्लायर का पता',
          'supplier_address_hint': 'सप्लायर का पता दर्ज करें',
          'supplier_account_number': 'सप्लायर का खाता संख्या',
          'supplier_account_hint': 'सप्लायर का खाता संख्या दर्ज करें',
          'start_searching': 'खोजना शुरु करें !',
          'start_now': 'अभी शुरु करें !!!',
          'start_searching_almirah': 'अलमारी खोजना शुरु करें',
          'start_searching_company': 'कंपनी खोजना शुरु करें',
          'start_searching_customer': 'ग्राहक खोजना शुरु करें',
          'start_searching_customer_category': 'ग्राहक श्रेणी खोजना शुरु करें',
          'start_searching_godown': 'गोदाम खोजना शुरु करें',
          'start_searching_item': 'सामान खोजना शुरु करें',
          'start_searching_item_category': 'सामान श्रेण खोजना शुरु करें',
          'start_searching_item_variant': 'सामान का प्रकार खोजना शुरु करें',
          'start_searching_unit': 'मापतोल इकाई खोजना शुरु करें',
          'start_searching_order': 'आर्डर खोजना शुरु करें',
          'start_searching_purchased_item': 'खरीदा हुआ सामान खोजना शुरु करें',
          'start_searching_purchase_order': 'खरीद आदेश खोजना शुरु करें',
          'start_searching_store_room': 'स्टोररूम खोजना शुरु करें',
          'start_searching_supplier': 'सप्लायर खोजना शुरु करें',
          'add': 'जोडें',
          'add_more': 'अधिक जोड़ें',
          'update': 'अपडेट करें',
          'permission_denied_for_contacts':
              'संपर्क पढ़ने और लिखने के लिए अनुमति अस्वीकार कर दी गई',
          'error_msg': 'एक त्रुटि हुई है, पुनः प्रयास करें',
          'error': ' त्रुटि संदेश',
          'alert': 'चेतावनी',
          'success': 'सफलता संदेश',
          'already_exist_msg': 'पहले से ही मौजूद है',
          'cancel': 'रद्द करें',
          'color': 'रंग',
          'model': 'मॉडल',
          'size': 'साइज',
          'price': 'मूल्य',
          'write_diary': 'डायरी लिखें',
          'set_conversion_value': 'कन्वर्शन वैल्यू सेट करे ',
          'conversion_value_hint': 'कन्वर्शन वैल्यू सेट करे या इसे हटाएँ',
          'no_internet_title': 'इंटरनेट नहीं है',
          'no_internet_msg':
              'अपना इंटरनेट कनेक्शन जांचें या हिंदी कीबोर्ड का उपयोग करें',
          'close': 'बंद करे',
          'name': 'नाम',
          'choose_almirah': 'अलमारी चुनें',
          'confirm': 'पुष्टि करें',
          'created_at': 'बनाया गया',
          'updated_at': 'अपडेट किया गया',
          'shop_or_business_name': 'दुकान/बिज़नेस का नाम',
          'phone': 'मोबाइल',
          'nickname': 'उपनाम',
          'address': 'पता',
          'fullname': 'पूरा नाम : ',
          'shortname': 'संक्षिप्त नाम : ',
          'current_quantity': 'वर्तमान मात्रा : ',
          'receipt_share_subject': 'दयाल हार्डवेयर की तरफ से रसीद',
          'thank_msg': 'आपसे फिर मिलने की उम्मीद है।',
          'exit_app_msg': 'क्या आप इस ऐप से बाहर निकलना चाहते हैं?',
          'yes': 'हां',
          'no': 'नहीं',
          'receipt_header': 'दयाल हार्डवेयर',
          'total': 'कुल',
          'number_of_searches': 'खोज की गयी संख्या : ',
          'number_of_almirah': 'अलमारी की संख्या : ',
          'number_of_store_room': 'स्टोररूम की संख्या : ',
          'number_of_customer': 'ग्राहक की संख्या : ',
          'number_of_item': 'सामान की संख्या : ',
          'number_of_row': "पंक्ति की संख्या : ",
          "number_of_column": "स्तंभ की संख्या : ",
          'alternate_phone': 'वैकल्पिक मोबाइल नंबर : ',
          'account_number': 'खाता संख्या : ',
          'conversion_value': 'मान',
          'enter_full_unit_first': 'पहले, इकाई का पूरा नाम दर्ज करें',
          'search_district_here': 'यहां जिला खोजें',
          'search_block_here': 'यहां प्रखंड/तहसील खोजें',
          'search_panchayat_here': 'यहां पंचायत खोजें',
          'search_village_here': 'यहां गांव/इलाका खोजें',
          'search_mohalla_here': 'यहां मोहल्ला/सोसाइटी खोजें',
          'district': 'जिला',
          'block': 'प्रखंड/तहसील',
          'panchayat': 'पंचायत',
          'village': 'गांव/इलाका',
          'mohalla': 'मोहल्ला/सोसाइटी',
          "no_district_found": 'कोई जिला नहीं मिला है।',
          "no_block_found": 'कोई प्रखंड/तहसील नहीं मिला है।',
          "no_panchyat_found": 'कोई पंचायत नहीं मिला है।',
          "no_village_found": 'कोई गांव/इलाका नहीं मिला है।',
          "no_mohalla_found": 'कोई मोहल्ला/सोसाइटी नहीं मिला है।',
          'add_open_space_godown':
              'सामान रखने के लिए गोदाम में खुली जगह जोड़ें। : ',
          'add_open_space_store_room':
              'सामान रखने के लिए स्टोररूम में खुली जगह जोड़ें। : ',
          'open_space': 'खुली जगह',
          'expiry_date': 'समाप्ति तिथि',
          'expiry_date_hint': 'समाप्ति तिथि अतीत में नहीं हो सकती है।',
          'purchase_date': 'क्रय तिथि',
          'payable_amount': 'देय राशि',
          'total_amount': 'कुल राशि',
          'discount': 'छूट',
          'total_amount_due': 'कुल बकाया राशि',
          'invoice': 'बिल',
          'rate': 'दर',
          'gst': 'जीएसटी'
        },
        'en_US': {
          'almirah': 'Almirah',
          'analytics': 'Analytics',
          'company': 'Company',
          'contact': 'Contacts',
          'customer': 'Customer',
          'customer_category': 'Customer category',
          'customer_category_n': 'Customer\ncategory',
          'diary': 'Dairy',
          'godown': 'Godown',
          'unit': 'Unit',
          'unit_n': 'Unit',
          'purchase_order': 'Purchase Order',
          'purchase_order_n': 'Purchase\nOrder',
          'purchased_item': 'Purchased item',
          'purchased_item_n': 'Purchased\nitem',
          'sales_order': 'Sales Order',
          'sales_order_n': 'Sales\nOrder',
          'item': 'Item',
          'item_category': 'Item category',
          'item_category_n': 'Item\ncategory',
          'item_variant': 'Item variant',
          'item_variant_n': 'Item\nvariant',
          'receipt': 'Receipt',
          'report': 'Report',
          'store_room': 'Storeroom',
          'store_room_n': 'Storeroom',
          'supplier': 'Supplier',
          'add_almirah': 'Add Almirah',
          'add_company': 'Add Company',
          'add_customer': 'Add Customer',
          'add_customer_category': 'Add Customer Category',
          'add_godown': 'Add Godown',
          'add_unit': 'Add Unit',
          'add_order': 'Add Order',
          'add_purchased_item': 'Add Purchased Item',
          'add_purchase_order': 'Add Purchase Order',
          'add_item': 'Add Item',
          'add_item_category': 'Add Item Category',
          'add_item_variant': 'Add Item Variant',
          'add_store_room': 'Add Storeroom',
          'add_supplier': 'Add Supplier',
          'update_almirah': 'Update Almirah',
          'update_company': 'Update Company',
          'update_customer': 'Update Customer',
          'update_customer_category': 'Update Customer Category',
          'update_godown': 'Update Godown',
          'update_unit': 'Update unit',
          'update_order': 'Update Order',
          'update_purchased_item': 'Update Purchased Item',
          'update_purchase_order': 'Update Purchase Order',
          'update_item': 'Update Item',
          'update_item_category': 'Update Item Category',
          'update_item_variant': 'Update Item Variant',
          'update_store_room': 'Update Storeroom',
          'update_supplier': 'Update Supplier',
          'search_almirah_here': 'Search almirah here',
          'search_company_here': 'Search company here.',
          'search_customer_here': 'Search customer here',
          'search_customer_category_here': 'Search customer category here',
          'search_godown_here': 'Search godown here',
          'search_item_here': 'Search item here',
          'search_item_variant_here': 'Search item variant here',
          'search_item_category_here': 'Search item category here.',
          'search_unit_here': 'Search unit here',
          "search_order_here": "Search order here",
          "search_purchased_item_here": "Search purchased item here",
          "search_purchase_order_here": "Search purchase order here",
          'search_receipt_here': 'Search receipt here',
          'search_store_room_here': 'Search storeroom here',
          'search_supplier_here': 'Search supplier here',
          'search_contact_here': 'Search contact here',
          'add_almirah_n': 'Add\nAlmirah',
          'view_almirah_n': 'View\nAlmirah',
          'add_company_n': 'Add\nCompany',
          'view_company_n': 'View\nCompany',
          'add_customer_n': 'Add\nCustomer',
          'view_customer_n': 'View\nCustomer',
          'add_customer_category_n': 'Add Customer\nCategory',
          'view_customer_category_n': 'View Customer\nCategory',
          'add_godown_n': 'Add\nGodown',
          'view_godown_n': 'View\nGodown',
          'add_unit_n': 'Add\nUnit',
          'view_unit_n': 'View\nUnit',
          'add_order_n': 'Add\nOrder',
          'view_order_n': 'View\nOrder',
          'add_purchased_item_n': 'Add\nPurchased Item',
          'view_purchased_item_n': 'View\nPurchased Item',
          'add_purchase_order_n': 'Add\nPurchase Order',
          'view_purchase_order_n': 'View\nPurchase Order',
          'add_item_n': 'Add\nItem',
          'view_item_n': 'View\nItem',
          'add_item_category_n': 'Add Item\nCategory',
          'view_item_category_n': 'View Item\nCategory',
          'view_item_variant': 'View Item Variant',
          'add_item_variant_n': 'Add Item\nVariant',
          'view_item_variant_n': 'View Item\nVariant',
          'add_store_room_n': 'Add\nStoreroom',
          'view_store_room_n': 'View\nStoreroom',
          'add_supplier_n': 'Add\nSupplier',
          'view_supplier_n': 'View\nSupplier',
          'almirah_success_msg': 'Almirah has been successfully added.',
          'company_success_msg': 'Company has been successfully added.',
          'customer_success_msg': 'Customer has been successfully added.',
          'customer_category_success_msg':
              'Customer category has been successfully added.',
          'diary_success_msg': 'Diary has been successfully addded',
          'godown_success_msg': 'Godown has been successfully added',
          'unit_success_msg': 'Unit  has been successfully added.',
          'order_success_msg': 'Order has been successfully added.',
          'purchased_item_success_msg':
              'Purchased item has been successfully added.',
          'purchase_order_success_msg':
              'Purchase order has been successfully added.',
          'item_success_msg': 'Item has been successfully added.',
          'item_category_success_msg':
              'Item category has been successfully added.',
          'item_variant_success_msg':
              'Item variant has been successfully added.',
          'store_room_success_msg': 'Storeroom has been successfully added.',
          'supplier_success_msg': 'Supplier has been successfully added.',
          "almirah_updated_success_msg":
              "Almirah has been successfully updated.",
          'company_updated_success_msg':
              'Company has been successfully updated.',
          'customer_updated_success_msg':
              'Customer has been successfully updated.',
          'customer_category_updated_success_msg':
              'Customer category has been successfully updated.',
          'diary_updated_success_msg': 'Diary has been successfully updated',
          'godown_updated_success_msg': 'Godown has been successfully updated',
          'unit_updated_success_msg': 'Unit has been successfully updated.',
          'order_updated_success_msg': 'Order has been successfully updated.',
          'purchased_item_updated_success_msg':
              'Purchased item has been successfully updated.',
          'purchase_order_updated_success_msg':
              'Purchase order has been successfully updated.',
          'item_updated_success_msg': 'Item has been successfully updated.',
          'item_category_updated_success_msg':
              'Item category has been successfully updated.',
          'item_variant_updated_success_msg':
              'Item variant has been successfully updated.',
          'store_room_updated_success_msg':
              'Storeroom has been successfully updated.',
          'supplier_updated_success_msg':
              'Supplier has been successfully updated.',
          "no_almirah_found": "No Almirah Found",
          "no_company_found": "No Company Found",
          "no_contact_found": "No Contact Found",
          "no_customer_found": "No Customer Found",
          "no_customer_category_found": "No Customer_Category Found",
          "no_diary_found": "No Diary Found",
          "no_godown_found": "No godown found",
          "no_order_found": "No order found",
          "no_purchased_item_found": 'No Purchased Item Found',
          "no_purchase_order_found": 'No Purchase Order Found',
          "no_item_found": 'No Item Found',
          "no_item_category_found": 'No Item Category Found',
          "no_item_variant_found": 'No Item Variant Found',
          "no_store_room_found": 'No Storeroom Found',
          "no_supplier_found": 'No Supplier Found',
          "no_unit_found": 'No Unit Found',
          'no_almirah': 'No almirah has been added yet',
          'no_company': 'No Company has been added yet.',
          'no_customer': 'No Customer has been added yet.',
          'no_customer_category': 'No customer category has been added yet.',
          'no_diary': 'No diary has been wrote yet',
          'no_godown': 'No godown has been added yet',
          'no_order': 'No Order has been added yet.',
          'no_purchased_item': 'No purchased item has been added yet',
          'no_purchase_order': 'No purchase order has been added yet',
          'no_item': 'No Item has been added yet.',
          'no_item_category': 'No item category has been added yet.',
          'no_item_variant': 'No Item variant has been added yet.',
          'no_store_room': 'No Storeroom has been added yet.',
          'no_supplier': 'No Supplier has been added yet.',
          'no_unit': 'No unit has been added yet.',
          'add_no_almirah': 'Start adding almirah',
          'add_no_company': 'Start adding company',
          'add_no_customer': 'Start adding customer.',
          'add_no_customer_category': 'Start adding customer category',
          'add_no_diary': 'Start writing diary',
          'add_no_godown': 'Start adding godown',
          'add_no_unit': 'Start adding unit.',
          'add_no_purchase_order': 'Start adding purchase order.',
          'add_no_purchased_item': 'Start adding purchased item.',
          'add_no_item': 'Start adding item.',
          'add_no_item_category': 'Start adding item category.',
          'add_no_item_variant': 'Start adding item variant.',
          'add_no_store_room': 'Start adding storeroom.',
          'add_no_supplier': 'Start adding supplier.',
          'almirah_name': 'Almirah Name',
          'almirah_hint': 'Enter almirah name',
          'almirah_row': 'Number of Row',
          'almirah_row_hint': 'Enter number of row in the almirah',
          'almirah_column': 'Number of Column',
          'almirah_column_hint': 'Enter number of column in the almirah',
          'alternate_name': 'Alternate Name',
          'alternate_name_hint': 'Enter alternate name',
          'column': 'Column',
          'column_hint': 'Enter number of column',
          'company_name': 'Company Name',
          'company_name_hint': 'Enter company name.',
          'customer_mobile_number': 'Customer Mobile Number',
          'customer_mobile_number_hint': 'Enter customer mobile number',
          'customer_name': 'Customer Name',
          'customer_name_hint': 'Enter customer name',
          'customer_nick_name': 'Customer Nick Name',
          'customer_nick_name_hint': 'Enter customer nick name',
          'male': 'Male',
          'female': 'Female',
          'customer_address': 'Customer Address',
          'customer_address_hint': 'Enter customer address',
          'customer_account_number': 'Customer Account Number',
          'customer_account_hint': 'Enter customer account number',
          'customer_category_name': 'Customer Category',
          'customer_category_hint': 'Enter customer category name',
          'godown_name': 'Godown Name',
          'godown_name_hint': 'Enter a godown name',
          'item_name': 'Item Name',
          'item_name_hint': 'Enter a valid item name',
          'item_category_name': 'Item Category',
          'item_category_name_hint': 'Enter a valid item category',
          'item_description': 'Description About Item:',
          'item_description_hint': 'Enter something about the item.',
          'item_category_hint': 'Enter a valid item category',
          'unit_hint': 'Enter  ',
          'unit_full_name': '  Full Name:',
          'unit_full_name_hint': 'Enter   full name',
          'unit_short_name': '  Short Name:',
          'unit_short_name_hint': 'Enter   short name',
          'purchased_quantity': 'Purchased Quantity',
          'purchased_quantity_hint': 'Enter purchased quantity',
          "purchased_quantity_unit": 'Purchased quantity ',
          "purchasing_price_unit": "Purchased price ",
          'minimum_stock_description':
              'You will be alerted if the quantity is less than the minimum stock',
          'minimum_stock': 'Minimum stock quantity',
          'minimum_stock_unit': 'Minimum stock Unit',
          'pincode': 'Pincode',
          'pincode_hint': 'Enter six digit pin code',
          'purchasing_date': 'Purchasing Date',
          "purchasing_date_hint": "Can't Enter Future Date",
          'purchasing_price': 'Purchasing Price',
          'purchasing_price_hint': 'Enter purchasing price',
          'quantity': 'Quantity',
          'quantity_hint': 'Enter quantity',
          'row': 'Row',
          'row_hint': 'Enter number of row',
          "selling_price": "Selling Price",
          'selling_price_hint': 'Enter selling price',
          "selling_price_unit": "Selling price ",
          'store_room_name': 'Storeroom Name',
          'store_room_name_hint': 'Enter storeroom name',
          'supplier_mobile_number': 'Supplier Mobile Number',
          'supplier_mobile_number_hint': 'Enter supplier mobile number',
          'supplier_name': 'Supplier Name',
          'supplier_name_hint': 'Enter supplier name',
          'supplier_nick_name': 'Supplier Nick Name',
          'supplier_nick_name_hint': 'Enter supplier nick name',
          'supplier_shop_or_business_name': 'Supplier Shop/Business Name',
          'supplier_shop_or_business_name_hint':
              'Enter supplier shop/business name',
          'supplier_address': 'Supplier Address',
          'supplier_address_hint': 'Enter supplier address',
          'supplier_account_number': 'Supplier Account Number',
          'supplier_account_hint': 'Enter supplier account number',
          'start_searching': 'Start Searching !',
          'start_now': 'Start it RIGHT NOW !!!',
          'start_searching_almirah': 'Start Searching Almirah',
          'start_searching_company': 'Start Searching Company',
          'start_searching_customer': 'Start Searching Customer',
          'start_searching_customer_category':
              'Start Searching Customer Category',
          'start_searching_godown': 'Start Searching Godown',
          'start_searching_item': 'Start Searching Item',
          'start_searching_item_variant': 'Start Searching Item Variant',
          'start_searching_item_category': 'Start Searching Item Category',
          'start_searching_unit': 'Start Searching Unit',
          'start_searching_order': 'Start Searching Order',
          'start_searching_purchased_item': 'Start Searching Purchased Item',
          'start_searching_purchase_order': 'Start Searching Purchase Order',
          'start_searching_store_room': 'Start Searching Storeroom',
          'start_searching_supplier': 'Start Searching Supplier',
          'receipt_share_subject': 'Receipt from Dayal Hardware',
          'thank_msg': 'Hope to see you again.',
          'exit_app_msg': 'Do you want to exit this App?',
          'yes': 'Yes',
          'no': 'No',
          'receipt_header': 'Dayal Hardware',
          'total': 'Total',
          'add': 'Add',
          'add_more': 'Add More',
          'update': 'Update',
          'permission_denied_for_contacts':
              'Permission denied for contact read and write.',
          'error_msg': 'An error occured, try again',
          'error': 'Error',
          'alert': 'Alert',
          'success': 'Success',
          'already_exist_msg': 'Already exist',
          'cancel': 'Cancel',
          'color': 'Color',
          'model': 'Model',
          'size': 'Size',
          'price': 'Price',
          'set_conversion_value': 'Set conversion value',
          'conversion_value_hint': 'set conversion value or remove it',
          'no_internet_title': 'No Internet',
          'no_internet_msg':
              'Check your internet connection or use hindi keyboard',
          'description': 'Description',
          'no_purchased_item_available': 'No purchased record available',
          'close': 'Close',
          'name': 'Name',
          'choose_almirah': 'Choose almirah',
          'confirm': 'Confirm',
          'created_at': 'Created at',
          'updated_at': 'Updated at',
          'shop_or_business_name': 'Shop/Business Name : ',
          'phone': 'Mobile',
          'nickname': 'Nick Name : ',
          'address': 'Address : ',
          'fullname': 'Full Name : ',
          'shortname': 'Short Name : ',
          'current_quantity': 'Current Quantity : ',
          'number_of_searches': 'Number of Searches : ',
          'number_of_almirah': 'Number of Almirah : ',
          'number_of_store_room': 'Number of Storeroom : ',
          'number_of_customer': 'Number of Customer : ',
          'number_of_item': 'Number of Item : ',
          'number_of_row': "Number of Row : ",
          'number_of_column': "Number of Column : ",
          'alternate_phone': 'Alternate Phone : ',
          'account_number': 'Account Number : ',
          'conversion_value': 'Value',
          'enter_full_unit_first': 'First, Enter Full Name of the unit',
          'search_district_here': 'Search district here',
          'search_block_here': 'Search block here',
          'search_panchayat_here': 'Search panchayat here',
          'search_village_here': 'Search village/locality here',
          'search_mohalla_here': 'Search mohalla/society here',
          'district': 'District',
          'block': 'Block/Tehsil',
          'panchayat': 'Panchayat',
          'village': 'Village/Locality',
          'mohalla': 'Mohalla/Society',
          "no_district_found": 'No District Found',
          "no_block_found": 'No Block/Tehsil Found',
          "no_panchayat_found": 'No Panchayat Found',
          "no_village_found": 'No Village/Locality Found',
          "no_mohalla_found": 'No Mohalla/Society Found',
          'add_open_space_godown':
              'Add open space in the godown to keep items. : ',
          'add_open_space_store_room':
              'Add open space in the storeroom to keep items. : ',
          'openspace': 'Open Space',
          'expiry_date': 'Expiry date',
          'expiry_date_hint': "Expiry date can't be in the past.",
          'purchase_date': 'Purchase date',
          'payable_amount': 'Payable Amount',
          'total_amount': 'Total Amount',
          'discount': 'Discount',
          'total_amount_due': 'Total Amount Due',
          'invoice': 'INVOICE',
          'rate': 'Rate',
          'gst': 'GST',
        },
      };
}
